// Metadatos de cada herramienta. Datos puros: lo usa la app y el script de build
// que genera un HTML por ruta (títulos y descripciones para buscadores).

export const SITE = {
  name: 'tgb.cl',
  tagline: 'Herramientas útiles para Chile',
  url: 'https://tgb.cl',
  // Token de Cloudflare Web Analytics (Analytics y registros → Web Analytics → tgb.cl). Vacío = desactivado.
  cfAnalyticsToken: 'cfe938f5775e4e7fb9062b41403dca5a',
  description:
    'Indicadores económicos, sueldo líquido, finiquito, feriados, sismos, clima, validador de RUT y más herramientas gratuitas para Chile.',
}

export const CATEGORIES = [
  { id: 'dinero', name: 'Dinero e indicadores', icon: 'Coins' },
  { id: 'trabajo', name: 'Trabajo e impuestos', icon: 'Briefcase' },
  { id: 'hogar', name: 'Hogar y transporte', icon: 'Sofa' },
  { id: 'vivo', name: 'Chile en vivo', icon: 'Radio' },
  { id: 'calendario', name: 'Calendario y hora', icon: 'Calendar' },
  { id: 'tramites', name: 'Trámites y datos', icon: 'FileText' },
]

export const TOOLS = [
  {
    slug: 'uf-hoy',
    landing: true,
    code: 'uf',
    title: 'Valor UF hoy',
    short: 'Valor de la UF de hoy, variación y conversor a pesos.',
    description: 'Valor de la UF hoy en Chile, actualizado cada día: variación, historial de los últimos 30 días y conversor de UF a pesos.',
    category: 'dinero',
    icon: 'TrendingUp',
    keywords: 'uf hoy valor uf unidad de fomento hoy pesos',
  },
  {
    slug: 'dolar-hoy',
    landing: true,
    code: 'dolar',
    title: 'Dólar hoy',
    short: 'Dólar observado de hoy, variación y conversor a pesos.',
    description: 'Valor del dólar hoy en Chile (dólar observado del Banco Central): variación, historial de los últimos 30 días y conversor a pesos.',
    category: 'dinero',
    icon: 'TrendingUp',
    keywords: 'dolar hoy precio dolar observado chile pesos',
  },
  {
    slug: 'euro-hoy',
    landing: true,
    code: 'euro',
    title: 'Euro hoy',
    short: 'Valor del euro de hoy, variación y conversor a pesos.',
    description: 'Valor del euro hoy en Chile: variación, historial de los últimos 30 días y conversor de euros a pesos.',
    category: 'dinero',
    icon: 'TrendingUp',
    keywords: 'euro hoy valor euro chile pesos',
  },
  {
    slug: 'utm-hoy',
    landing: true,
    code: 'utm',
    title: 'Valor UTM',
    short: 'Valor de la UTM de este mes y conversor a pesos.',
    description: 'Valor de la UTM (Unidad Tributaria Mensual) de este mes en Chile, historial y conversor de UTM a pesos.',
    category: 'dinero',
    icon: 'TrendingUp',
    keywords: 'utm valor utm mes unidad tributaria mensual',
  },
  {
    slug: 'indicadores',
    title: 'Indicadores económicos',
    short: 'UF, UTM, dólar, euro e IPC de hoy, con gráfico histórico.',
    description: 'Valor de la UF, UTM, dólar observado, euro e IPC hoy en Chile, con historial de los últimos 30 días.',
    category: 'dinero',
    icon: 'TrendingUp',
    keywords: 'uf hoy utm dolar euro ipc valor',
  },
  {
    slug: 'conversor',
    share: true,
    title: 'Conversor UF, UTM y monedas',
    short: 'Convierte entre pesos, UF, UTM, dólares y euros.',
    description: 'Convierte pesos chilenos a UF, UTM, dólares y euros (y viceversa) con los valores del día.',
    category: 'dinero',
    icon: 'ArrowLeftRight',
    keywords: 'convertir uf a pesos utm dolar euro clp',
  },
  {
    slug: 'reajuste-arriendo',
    share: true,
    title: 'Reajuste de arriendo',
    short: 'Calcula el reajuste de tu arriendo según la variación de la UF.',
    description: 'Calcula cuánto sube tu arriendo entre dos fechas según la variación de la UF (reajuste por IPC).',
    category: 'dinero',
    icon: 'House',
    keywords: 'reajuste arriendo ipc uf variacion',
  },
  {
    slug: 'dividendo',
    share: true,
    title: 'Simulador de crédito hipotecario',
    short: 'Estima el dividendo mensual de un crédito en UF.',
    description: 'Simula el dividendo mensual de un crédito hipotecario en UF según monto, pie, plazo y tasa.',
    category: 'dinero',
    icon: 'Landmark',
    keywords: 'dividendo credito hipotecario simulador uf tasa pie',
  },
  {
    slug: 'credito-consumo',
    share: true,
    title: 'Simulador de crédito de consumo',
    short: 'Cuota, CAE y costo total de un crédito de consumo.',
    description: 'Simula un crédito de consumo en Chile: cuota mensual, CAE (carga anual equivalente) y cuánto pagas en total, con seguros y gastos.',
    category: 'dinero',
    icon: 'CreditCard',
    keywords: 'credito consumo cae carga anual equivalente cuota prestamo banco tasa simulador',
  },
  {
    slug: 'comparador-historico',
    share: true,
    title: 'Inflación y valor del dinero',
    short: 'Cuánto valen hoy los pesos de otra fecha, en UF y en dólares.',
    description: 'Calcula cuánto equivale hoy un monto en pesos de cualquier fecha desde 1977 según la UF, y compáralo con haberlo guardado en dólares.',
    category: 'dinero',
    icon: 'Hourglass',
    keywords: 'inflacion ipc valor del dinero historico uf dolar fecha pesos antiguos equivalente hoy',
  },
  {
    slug: 'apv',
    share: true,
    title: 'APV: régimen A o B',
    short: 'Qué régimen de APV te conviene según tu sueldo.',
    description: 'Compara el APV régimen A (bonificación del 15%) con el régimen B (rebaja de impuestos) según tu sueldo y descubre cuál te conviene.',
    category: 'dinero',
    icon: 'PiggyBank',
    keywords: 'apv ahorro previsional voluntario regimen a b bonificacion 15 impuesto',
  },
  {
    slug: 'compras-extranjero',
    share: true,
    title: 'Compras en el extranjero',
    short: 'Cuánto pagas con IVA y arancel en AliExpress, Temu o Amazon.',
    description: 'Calcula cuánto pagas realmente al comprar en AliExpress, Temu, Shein o Amazon desde Chile: IVA del 19%, arancel sobre USD 500 y dólar del día.',
    category: 'dinero',
    icon: 'Plane',
    keywords: 'compras extranjero aliexpress temu shein amazon iva 19 arancel aduana 500 dolares importar',
  },
  {
    slug: 'widget',
    title: 'Widget de indicadores',
    short: 'Pon la UF y el dólar del día en tu sitio web, gratis.',
    description: 'Widget gratuito para mostrar la UF, el dólar, el euro y la UTM del día en tu sitio web, blog o tienda. Copia y pega el código.',
    category: 'dinero',
    icon: 'Copy',
    keywords: 'widget uf dolar sitio web blog wordpress indicadores gratis embeber',
  },
  {
    slug: 'ahorro',
    share: true,
    title: 'Ahorro e interés',
    short: 'Cuánto ganas ahorrando cada mes o con un depósito a plazo.',
    description: 'Simula cuánto crece tu ahorro en Chile con interés compuesto, en pesos o en UF, y cuánto ganas con un depósito a plazo.',
    category: 'dinero',
    icon: 'Sprout',
    keywords: 'ahorro interes compuesto deposito a plazo rentabilidad invertir cuanto gano banco fondo mutuo',
  },
  {
    slug: 'descuentos',
    share: true,
    title: 'Descuentos y ofertas',
    short: 'Precio con descuento, ofertas reales y qué promoción conviene.',
    description: 'Calcula precios con descuento, descuentos sucesivos y compara promociones (3x2, 50% en la segunda unidad) para CyberDay y Black Friday.',
    category: 'dinero',
    icon: 'BadgePercent',
    keywords: 'descuento porcentaje oferta cyberday black friday 3x2 segunda unidad rebaja precio',
  },
  {
    slug: 'datos-legales',
    title: 'Datos legales 2026',
    short: 'Sueldo mínimo, topes, tramos de impuesto y más valores del año.',
    description: 'Todos los valores legales de 2026 en Chile: ingreso mínimo, topes imponibles, tramos del impuesto único, comisiones AFP, retención de honorarios y más.',
    category: 'trabajo',
    icon: 'Scale',
    keywords: 'sueldo minimo ingreso minimo 2026 tope imponible tramos impuesto unico comisiones afp valores legales',
  },
  {
    slug: 'sueldo-liquido',
    share: true,
    title: 'Calculadora de sueldo líquido',
    short: 'De bruto a líquido y de líquido a bruto, con AFP, salud e impuesto.',
    description: 'Calcula tu sueldo líquido 2026 en Chile: AFP, Fonasa o Isapre, seguro de cesantía e impuesto único. También de líquido a bruto.',
    category: 'trabajo',
    icon: 'Wallet',
    keywords: 'sueldo liquido bruto afp fonasa isapre impuesto unico cesantia',
  },
  {
    slug: 'boleta-honorarios',
    share: true,
    title: 'Boleta de honorarios',
    short: 'Calcula la retención 2026 (15,25%) en bruto o líquido.',
    description: 'Calcula el monto bruto, líquido y la retención de una boleta de honorarios 2026 (15,25%).',
    category: 'trabajo',
    icon: 'ReceiptText',
    keywords: 'boleta honorarios retencion 15,25 bruto liquido sii',
  },
  {
    slug: 'iva',
    share: true,
    title: 'Calculadora de IVA',
    short: 'Agrega o quita el 19% de IVA a un monto.',
    description: 'Calcula el IVA (19%) en Chile: neto a bruto, bruto a neto y monto del impuesto.',
    category: 'trabajo',
    icon: 'Percent',
    keywords: 'iva 19 neto bruto calcular',
  },
  {
    slug: 'finiquito',
    share: true,
    title: 'Calculadora de finiquito',
    short: 'Indemnización por años de servicio, aviso previo y vacaciones.',
    description: 'Calcula tu finiquito en Chile: indemnización por años de servicio, mes de aviso y vacaciones proporcionales según la causal de despido.',
    category: 'trabajo',
    icon: 'FileSignature',
    keywords: 'finiquito indemnizacion años de servicio despido aviso previo vacaciones proporcionales necesidades de la empresa renuncia',
  },
  {
    slug: 'horas-extra',
    share: true,
    title: 'Calculadora de horas extra',
    short: 'Valor de la hora extra con jornada de 42 horas y recargo del 50%.',
    description: 'Calcula el valor de la hora extra en Chile 2026 con la jornada de 42 horas (Ley 40 horas) y el recargo legal del 50%.',
    category: 'trabajo',
    icon: 'Timer',
    keywords: 'horas extra extraordinarias valor hora recargo 50 jornada 42 horas ley 40 horas',
  },
  {
    slug: 'gratificacion',
    share: true,
    title: 'Gratificación legal',
    short: 'Calcula el 25% mensual con el tope de 4,75 ingresos mínimos.',
    description: 'Calcula la gratificación legal mensual en Chile (artículo 50): 25% de la remuneración con tope de 4,75 ingresos mínimos al año.',
    category: 'trabajo',
    icon: 'Gift',
    keywords: 'gratificacion legal articulo 50 tope 4,75 ingreso minimo mensual',
  },
  {
    slug: 'licencia-medica',
    share: true,
    title: 'Calculadora de licencia médica',
    short: 'Cuánto te pagan de subsidio durante una licencia médica.',
    description: 'Calcula el subsidio por licencia médica en Chile: promedio de los últimos 3 meses, días de carencia y cuánto recibes en total.',
    category: 'trabajo',
    icon: 'HeartPulse',
    keywords: 'licencia medica subsidio incapacidad laboral cuanto pagan dias carencia fonasa isapre compin',
  },
  {
    slug: 'vacaciones',
    share: true,
    title: 'Calculadora de vacaciones',
    short: 'Días de vacaciones al año, progresivos y acumulados.',
    description: 'Calcula cuántos días de vacaciones te corresponden en Chile: feriado legal de 15 días, vacaciones progresivas y días acumulados.',
    category: 'trabajo',
    icon: 'Sunset',
    keywords: 'vacaciones dias feriado legal progresivas cuantos dias me corresponden acumulados',
  },
  {
    slug: 'farmacias-de-turno',
    share: true,
    title: 'Farmacias de turno',
    short: 'La farmacia de turno más cercana, con horario y teléfono.',
    description: 'Encuentra la farmacia de turno más cercana en Chile hoy, con dirección, horario, teléfono y mapa. Datos oficiales del MINSAL.',
    category: 'hogar',
    icon: 'Pill',
    keywords: 'farmacia de turno hoy cerca abierta 24 horas noche minsal farmanet',
  },
  {
    slug: 'bencinas',
    share: true,
    title: 'Precio de bencinas',
    short: 'Dónde cargar más barato: 93, 95, 97, diésel y parafina por comuna.',
    description: 'Precios de bencina 93, 95, 97, diésel y parafina en todas las bencineras de Chile. Encuentra la más barata en tu comuna o cerca de ti.',
    category: 'hogar',
    icon: 'Fuel',
    keywords: 'precio bencina gasolina 93 95 97 diesel parafina kerosene bencinera barata comuna cerca',
  },
  {
    slug: 'costo-viaje',
    share: true,
    title: 'Costo de un viaje en auto',
    short: 'Combustible y peajes de un viaje, y cuánto pone cada uno.',
    description: 'Calcula cuánto cuesta un viaje en auto en Chile: combustible según rendimiento y precio actual, peajes y costo por persona.',
    category: 'hogar',
    icon: 'Car',
    keywords: 'costo viaje auto bencina rendimiento km litro peajes dividir',
  },
  {
    slug: 'consumo-electrico',
    share: true,
    title: 'Consumo eléctrico',
    short: 'Cuánto gastan tus aparatos en la cuenta de la luz.',
    description: 'Calcula cuánto consume cada aparato eléctrico de tu casa en kWh y pesos al mes: estufa, refrigerador, hervidor, aire acondicionado y más.',
    category: 'hogar',
    icon: 'Zap',
    keywords: 'consumo electrico luz kwh cuenta estufa electrica aparatos gasto enel boleta',
  },
  {
    slug: 'dividir-cuenta',
    share: true,
    title: 'Dividir la cuenta',
    short: 'Divide entre amigos con propina del 10% y redondeo.',
    description: 'Divide la cuenta del restaurante entre amigos, en partes iguales o según lo que consumió cada uno, con propina del 10%.',
    category: 'hogar',
    icon: 'UtensilsCrossed',
    keywords: 'dividir cuenta propina 10 restaurante amigos pagar partes iguales',
  },
  {
    slug: 'sismos',
    title: 'Sismos en Chile',
    short: 'Últimos temblores con magnitud, ubicación y mapa.',
    description: 'Últimos sismos y temblores en Chile en tiempo real: magnitud, ubicación, profundidad y mapa interactivo.',
    category: 'vivo',
    icon: 'Activity',
    keywords: 'sismos temblor terremoto ultimo sismo chile magnitud mapa',
  },
  {
    slug: 'clima',
    title: 'Clima y radiación UV',
    short: 'Pronóstico de 7 días, índice UV y calidad del aire por comuna.',
    description: 'Pronóstico del tiempo para 7 días, índice de radiación UV y calidad del aire (MP2,5) en cualquier comuna de Chile.',
    category: 'vivo',
    icon: 'CloudSun',
    keywords: 'clima tiempo pronostico radiacion uv indice calidad del aire mp2,5 smog comuna lluvia temperatura',
  },
  {
    slug: 'olas',
    share: true,
    title: 'Olas y mar',
    short: 'Altura de las olas, viento y temperatura del agua por playa.',
    description: 'Pronóstico de olas en Chile: altura, período y dirección del oleaje, viento y temperatura del mar en las principales playas.',
    category: 'vivo',
    icon: 'Waves',
    keywords: 'olas surf pronostico mar oleaje temperatura agua playa marejada viento',
  },
  {
    slug: 'feriados',
    title: 'Feriados de Chile',
    short: 'Próximo feriado, calendario anual y fines de semana largos.',
    description: 'Calendario de feriados de Chile: próximo feriado, lista completa del año, irrenunciables y fines de semana largos.',
    category: 'calendario',
    icon: 'CalendarDays',
    keywords: 'feriados chile proximo feriado fin de semana largo irrenunciable',
  },
  {
    slug: 'dias-habiles',
    share: true,
    title: 'Calculadora de días hábiles',
    short: 'Cuenta días hábiles entre fechas o suma plazos.',
    description: 'Cuenta los días hábiles entre dos fechas en Chile descontando feriados, o calcula la fecha de vencimiento de un plazo.',
    category: 'calendario',
    icon: 'CalendarCheck',
    keywords: 'dias habiles plazo contar fechas feriados',
  },
  {
    slug: 'fechas-clave',
    title: 'Fechas clave del año',
    short: 'Permiso de circulación, Operación Renta, contribuciones y más.',
    description: 'Calendario de fechas importantes en Chile: permiso de circulación, revisión técnica según patente, Operación Renta, contribuciones y feriados. Descárgalo a tu calendario.',
    category: 'calendario',
    icon: 'BellRing',
    keywords: 'fechas importantes calendario permiso de circulacion revision tecnica patente operacion renta contribuciones vencimientos',
  },
  {
    slug: 'fines-de-semana-largos',
    title: 'Planificador de fines de semana largos',
    short: 'Qué días pedir para tener más días libres seguidos.',
    description: 'Descubre qué días de vacaciones pedir para aprovechar los feriados de Chile y lograr fines de semana largos de 4, 5 o más días.',
    category: 'calendario',
    icon: 'TreePalm',
    keywords: 'fin de semana largo feriados vacaciones puente dias libres planificar interferiado',
  },
  {
    slug: 'cambio-de-hora',
    title: 'Cambio de hora en Chile',
    short: 'Cuándo se atrasa o adelanta el reloj, con cuenta regresiva.',
    description: 'Próximo cambio de hora en Chile con cuenta regresiva, hora oficial actual en el continente, Aysén, Magallanes y Rapa Nui.',
    category: 'calendario',
    icon: 'Clock',
    keywords: 'cambio de hora horario de invierno verano reloj atrasar adelantar magallanes aysen rapa nui',
  },
  {
    slug: 'rut',
    title: 'Validador de RUT',
    short: 'Valida, formatea y calcula el dígito verificador.',
    description: 'Valida un RUT chileno, calcula el dígito verificador y formatea con puntos y guion. Genera RUT de prueba.',
    category: 'tramites',
    icon: 'IdCard',
    keywords: 'rut validar digito verificador formatear generar',
  },
  {
    slug: 'comunas',
    title: 'Regiones y comunas de Chile',
    short: 'Las 346 comunas con código CUT, descargables en CSV y JSON.',
    description: 'Listado de las 16 regiones y 346 comunas de Chile con código único territorial (CUT), provincia y superficie. Descarga en CSV o JSON.',
    category: 'tramites',
    icon: 'Map',
    keywords: 'regiones comunas chile listado codigo cut provincia json csv descargar',
  },
  {
    slug: 'pension-alimentos',
    share: true,
    title: 'Pensión de alimentos',
    short: 'Monto mínimo legal según la cantidad de hijos.',
    description: 'Calcula la pensión de alimentos mínima en Chile según la Ley 14.908: 40% del ingreso mínimo por un hijo y 30% por hijo si son dos o más.',
    category: 'tramites',
    icon: 'Users',
    keywords: 'pension alimentos minima hijos ley 14908 monto cuanto pagar alimentos tribunal familia',
  },
  {
    slug: 'tramites',
    title: 'Directorio de trámites',
    short: 'Enlaces oficiales: ClaveÚnica, SII, Registro Civil y más.',
    description: 'Accesos directos a los trámites y servicios más usados en Chile: ClaveÚnica, SII, Registro Civil, AFC, Fonasa y más.',
    category: 'tramites',
    icon: 'Building2',
    keywords: 'tramites claveunica sii registro civil certificado afc fonasa',
  },
  {
    slug: 'emergencias',
    title: 'Teléfonos de emergencia',
    short: 'Ambulancia, bomberos, carabineros y otros números útiles.',
    description: 'Números de emergencia en Chile: SAMU 131, Bomberos 132, Carabineros 133, PDI 134 y otros teléfonos útiles.',
    category: 'tramites',
    icon: 'Siren',
    keywords: 'emergencia telefono samu bomberos carabineros pdi numero',
  },
]
